# Main window
HEIGHT_MAIN = 40
WIDTH_MAIN = 120

# Combat
COMBAT_ACTOR_HEIGHT = 5
COMBAT_ACTOR_WIDTH = 23
COMBAT_ACTOR_MARGIN_BAR = 3
COMBAT_ACTOR_MARGIN_NAME = 2
COMBAT_CARD_HAND_PUSH = 2
COMBAT_TARGET_MARGIN_X = 2
COMBAT_TARGET_MARGIN_Y = 1

# Card
HEIGHT_CARD = 10
WIDTH_CARD = 14
GAP_CARD = 1

# Margins
MARGIN_COMBAT_HAND_DOWN = 0
MARGIN_COMBAT_HAND_LEFT = 0
