exp_name: jaw/a2c-transf
num_episodes: 1.0e+6
log_every: 100
eval_every: 100
save_every: 10000
gamma: 0.99
coef_value: 0.50
coef_entropy_max: 0.05
coef_entropy_min: 0.01
coef_entropy_elbow: 2.5e+5 
max_grad_norm: 0.50

model:
  dim_card: 4
  num_heads: 4

optimizer:
  name: Adam
  kwargs:
    lr: 2.5e-5
    # nesterov: True
    # momentum: 0.90
