exp_name: a2c/jaw/newera
num_episodes: 1.0e+6
log_every: 100
eval_every: 100
save_every: 1000
gamma: 0.99
coef_entropy_max: 0.050
coef_entropy_min: 0.010
coef_entropy_elbow: 2.5e+5
max_grad_norm: 0.500

model_actor:
  dim_card: 32

model_critic:
  dim_card: 32

optimizer_actor:
  name: Adam
  kwargs:
    lr: 2.5e-5

optimizer_critic:
  name: Adam
  kwargs:
    lr: 1.0e-4
