exp_name: jaw/delete
num_episodes: 1.0e+6
buffer_size: 5.0e+3
batch_size: 64
eval_every: 25
save_every: 10000

model: 
  name: EmbeddingMLP
  kwargs:
    linear_sizes: [1024, 1024, 1024]

optimizer:
  name: SGD
  kwargs:
    lr: 1.0e-3
    # nesterov: True
    # momentum: 0.90

# Explorer
episode_elbow: 5.0e+4
value_start: 1
value_end: 1.0e-1
