exp_name: test-jaw-3
num_episodes: 2.0e+4
buffer_size: 1.0e+3
batch_size: 48
eval_every: 5

model: 
  name: EmbeddingMLP
  kwargs:
    card_name_embedding_size: 5
    state_embedding_size: 3
    linear_sizes: [256, 256, 256, 256]

optimizer:
  name: SGD
  kwargs:
    lr: 1.0e-3
    nesterov: True
    momentum: 0.90

# Explorer
episode_elbow: 2.5e+3
value_start: 1
value_end: 1.0e-3
